exp:
  name: "baseline"
  savedir: "./logs"
  tensorboard_dir: "./tensorboard"
  debug: False

# wandb_run: 'b50-trail2-split2-t2-div4on40'
wandb_run: 'base2022'
wandb_name: 'continual-generative'
data_folder: '/home/fengjw/solf/data/'
#Model Cfg
model: "generative"  #"regularization" #"incmodel"
convnet: 'resnet18' #modified_resnet32, resnet18
train_head: 'softmax'
infer_head: 'softmax'
channel: 64
use_bias: False
last_relu: False

der: False
use_aux_cls: False
aux_n+1: False
distillation: "none"
temperature: 2

reuse_oldfc: False 
weight_normalization: False
val_per_n_epoch: -1 # Validation Per N epoch. -1 means the function is off.
save_ckpt: True
save_mem: True
load_mem: False


#Optimization;Training related
task_max: 10
lr_min: 0.00005
lr: 0.1
weight_decay: 0.0005
dynamic_weight_decay: False
scheduler: 'multistep'
scheduling:
  - 100
  - 120
lr_decay: 0.1
optimizer: "sgd"
epochs: 170
resampling: False
warmup: True
warmup_epochs: 10
lambda: 0.1

postprocessor:
  enable: False
  type: 'bic' #'bic', 'wa'
  epochs: 1
  batch_size: 128
  lr: 0.1
  scheduling:
    - 60
    - 90
    - 120
  lr_decay_factor: 0.1
  weight_decay: 0.0005

decouple:
  enable: True # TODO 
  epochs:  50 
  fullset: False
  lr: 0.05 
  scheduling:
    - 15
    - 30 
  lr_decay: 0.1
  weight_decay: 0.0005
  temperature: 5.0

pretrain:
  epochs: 200
  lr: 0.1
  scheduling:
    - 60
    - 120
    - 160
  lr_decay: 0.1
  weight_decay: 0.0005


# Dataset Cfg
dataset: "cifar100" #'imagenet100', 'cifar100'
trial: 2
increment: 10 # 25 10 5 for b50
batch_size: 128
workers: 8
validation: 0 # Validation split (0. <= x <= 1.)
random_classes: False #Randomize classes order of increment
start_class: 0 # number of tasks for the first step, start from 0. !50! for b50
start_task: 0
max_task: # Cap the number of task

#Memory
coreset_strategy: "iCaRL"  # iCaRL, random
mem_size_mode: "uniform_fixed_total_mem" #uniform_fixed_per_cls, uniform_fixed_total_mem
memory_size: 2000 # Max number of storable examplars
fixed_memory_per_cls: 20 # the fixed number of exemplars per cls

# Misc
device: 0 #GPU index to use, for cpu use -1
seed: 1993

